department-of-veterans-affairs/lighthouse-platform-backend

build.sh

This PR is an attempt to fix the issue of containers inside of Jenkins from using cached images. This will tag the images we create with the build number and make sure that the docker compose down removes the image.

add removal and unique build name to docker compose

---

Gemfile
Gemfile.lock
app/api/v0/consumers.rb
app/api/validators/malicious_url_protection.rb
app/models/malicious_url.rb
db/migrate/20220314212117_create_malicious_urls.rb
db/schema.rb
db/seeds.rb
spec/api/utilities_spec.rb
spec/api/v0/consumers_spec.rb
spec/factories/malicious_url.rb
spec/spec_helper.rb
spec/support/vcr_cassettes/urlhaus/malicious_urls_200.yml

Malicious URL list in the implementation is only downloaded and stored once.
We can implement a background job in the future to keep our list up to date if needed (urlhaus mentions their list is updated every 5 minutes)
List this implementation is pulling from can be found here: https://urlhaus.abuse.ch/downloads/text/

API-14244: Investigate malicious url block list options for LCMS

---

db/seeds.rb

Allows re-running of this without first deleting all existing data in the database.
https://github.com/zdennis/activerecord-import/#duplicate-key-ignore

ignore duplicate malicious urls

---

app/api/v0/providers.rb

Release notes sent from release notes repo are url encoded to prevent issues with quotation marks, etc. LCMS needs to decode the release note content string before storing.

decode release notes from release notes repo

---

.rubocop.yml
app/services/okta/base_service.rb

Corrects the 400 from sending in a sawyer resource. This will be needed even with the upcoming Oktakit changes. 
Interesting to test. Have to create an auth server and provide that auth_server_access_key. Then overwrite the default `ALL_CLIENTS` in the `conditions.clients.include` and THEN apply through LPB.
Steps:
Create Auth Server
Use Oktakit to update Auth Server Default policy. -> Remove `ALL_CLIENTS` (I added an application ID just to mock) Without removing the `ALL_CLIENTS` it simply stayed `ALL_CLIENTS` even after signup.
Add Auth Server ID to `application.yml` to whatever oauth API you'll be signing up for (I used `verification` ApiRef)
Apply through LPB

fixes 400 on update_policy

---

app/api/v0/entities/consumer_application_entity.rb

This issue was causing the developer-portal frontend to not display oauth information on the sandbox signup success page.

client id in response is not what developer-portal expects

---

app/api/v0/entities/legacy/api_provider_category_entity.rb
app/api/v0/providers.rb

pass environment option through to the entity that cares about it
this allows picking an environment on api request, which allows the portal to get only one metadata url back in the providers response
also realized categories on the left sidebar wasnt being sorted by name

API-11956/additional-tweaks

---

app/api/v0/providers.rb
db/seeds.rb
spec/api/v0/providers_spec.rb
spec/factories/provider.rb

to make this work with grape-swagger as well as a default postman request, the two array types had to be comma-delimited and use a `coerce_with` to modify a string to an array.

Add provider endpoint

---

app/models/event.rb
config/initializers/scheduler.rb

Prevents multiple drift jobs from being sent to Slack via the multiple containers.

prevent multiple drift jobs

---

app/api/v0/consumers.rb
app/helpers/production_request_helper.rb
app/models/api.rb
app/models/apis_production_request.rb
app/models/production_request.rb
app/models/production_request_contact.rb
db/migrate/20220928201902_create_production_requests.rb
db/migrate/20220928204902_create_apis_production_requests.rb
db/migrate/20220930124413_create_production_request_contacts.rb
db/schema.rb
spec/api/v0/consumers_spec.rb
spec/models/production_request_spec.rb

- provides the ability to store off data sent to the `/platform-backend/v0/consumers/production-requests` endpoint.

[API-18379] - Persist "ProductionRequest" form data

---

app/api/v0/providers.rb

Despite my best efforts to make the Swagger placeholder text actually accurate, the end result was to give more emphasis on these fields needing to be comma separated. Not happy with this solution but based on research it seems this is not something that has been solved.
The root issue is that with using multiple lines, when you post sandbox and production the `api_environments_attributes[environments_attributes][name]` field it will show up twice without a trailing `[]` on it causing the backend to only receive the last value.
```
api_environments_attributes[environments_attributes][name]: sandbox
api_environments_attributes[environments_attributes][name]: production
```

[API-21296] Update field descriptions to make it more clear

---

.github/workflows/codeql.yml

[Original Issue](https://vajira.max.gov/browse/API-22129)
Updates CodeQL GitHub Action to V2.

[API-22129] - Update codeql github action to v2

---

.github/workflows/create-auto-deploy-maintenance-request.yml

[Original Issue](https://vajira.max.gov/browse/API-14772)
When we first tried to run the auto-deploy workflows against the DevOps repo, we encountered the following error in the `create_mr` step of the `Create Auto Deploy Maintenance Request` workflow ::
```
GraphQL: Could not resolve to a Repository with the name 'department-of-veterans-affairs/lighthouse-devops-support'. (repository)
```
Looks like we might need to re-login using the DevOps github creds  in that step.  This PR adds that re-login functionality.

[API-14772] - add logic to re-login with the devops creds

---

.github/workflows/auto-deploy-to-production.yml
.github/workflows/create-auto-deploy-maintenance-request.yml

[Original Issue](https://vajira.max.gov/browse/API-14772)
On the initial run of the auto deploy workflows, we ran into this error when attempting to add or remove labels from existing PRs.
```
Message: va-bot does not have the correct permissions to execute `RemoveLabelsFromLabelable`, Locations: [{Line:1 Column:62}]
```
This PR adds logic to explicitly authenticate to the GitHub cli as the non va-bot user.

[API-14772] - Fix PR label add/remove GHA steps

---

lib/tasks/lpb.rake

https://vajira.max.gov/browse/API-22785
Dump provided by @mramirez-va revealed that my previous audit missed veteran verification also has a `ccgInfo` part of it's `oauth_info` so missing that in the config of the rake task caused it to break during the deployment.

[API-22785] - Add CCG path to rake task for veteran verification

---

app/services/okta/base_service.rb

https://vajira.max.gov/browse/API-24383
Oauth ACG signups aren't properly setting the credentials property in the Okta payload. This is a legacy bug from the migration form `developer-portal-backend` to `lighthouse-platform-backend` which was recently uncovered.

[API-24383] - Update how credentials payload key is constructed

---

app/models/api.rb
spec/factories/api_metadata.rb
spec/factories/apis.rb
spec/models/api_spec.rb

Original Issue :: [API-25451](https://vajira.max.gov/browse/API-25451)
- Fixes bug in `api.locate_auth_types` that would raise when either `acgInfo` or `ccgInfo` was not present in the `api.api_metadatum.oauth_info` hash.

[API-25451] - Fix bug with locating auth types

---

.github/workflows/assets/maintenance-request.md

Removes the space between the `assignees` on the maintenance request markdown template to see if that will satisfy the GitHub Action Workflow.

Tweak MR markdown template file

---

.github/workflows/notify-security-alerts.yml

Original Issue :: [API-27989](https://jira.devops.va.gov/browse/API-27989)
- Adds a pretty basic GHA workflow that just checks for the existence of any code scanning alerts.
- If any alerts are found, it'll print out a message.
- Need this to be in `Master` before I can test it out and iterate on it further to add things such as Slack integration.

API-27989 - Add GHA workflow to monitor security alerts

---

app/api/v0/support.rb
spec/api/v0/support_spec.rb

Original Issue :: [API-29438](https://jira.devops.va.gov/browse/API-29438)
- Allows "Contact Us" form submissions to send emails to Marmoset in lower envs.
- I have updated the Dev and Staging `/dvp/$ENVIRONMENT/platform-backend/support_email` env vars in AWS to the values requested by Marmoset.  (see Jira ticket for details)

[API-29438] - Allow "Contact Us" form submission emails in lower envs

---

app/api/v0/entities/legacy/api_provider_entity.rb
db/migrate/20230111172809_add_well_known_configs.rb
db/migrate/20230125163247_add_audience_values.rb
db/migrate/20230208190820_add_audience_values_v2.rb
db/migrate/20230404203017_seed_new_information_architecture_fields.rb
db/migrate/20230622195231_seed_api_overview_page_data.rb
db/migrate/20230630195232_update_api_overview_page_data.rb
db/migrate/20230701151610_fix_category_url_slug_values.rb
db/migrate/20230703185426_update_api_overview_content_again.rb
db/migrate/20230703211827_update_api_descriptions.rb
db/migrate/20230703213757_update_title_for_higher_level_reviews.rb
db/migrate/20230705164852_update_veteran_verification_url_slug.rb
db/migrate/20230705192408_fix_overview_page_content.rb
db/migrate/20230706184309_actually_fix_overview_page_content.rb
db/migrate/20231016202941_add_stealth_launched_field.rb
db/migrate/20231017151330_default_stealth_launched_to_true.rb
db/schema.rb

https://jira.devops.va.gov/browse/API-30848
Adds `is_stealth_launched` field to the `api_metadata` database table and exposes it through `isStealthLaunched` on the `legacy.json` API endpoint. The reason for the two migrations was to first default the field to false (which all current APIs should have) and then set it to true so that all future APIs will start as being stealth launched so Okapi can audit newly added APIs before making them visible to the public.
I also removed the rake tasks that we were using in migrations as they were causing issues when spinning up a new instance of the app. In the future we shouldn't use this pattern of calling a rake task within a migration. (That was my bad idea and this is me realizing and reversing it)

[API-30848] - Add is_stealth_launched boolean field

---

app/controllers/home_controller.rb
spec/controllers/home_spec.rb
spec/factories/api_metadata.rb

https://jira.devops.va.gov/browse/API-30848
Add a conditional check to ensure that stealth launched APIs are not included in the site's sitemap.xml file.

[API-30848] - Sitemap handling for stealth launched APIs

---

Dockerfile.build

Original Issue :: [API-31348](https://jira.devops.va.gov/browse/API-31348)
- Removes the reference to the `vasdvp/health-apis-dev-tools:mvn-3.6-jdk-14` Docker image
- Replaces with a reference to the `ghcr.io/department-of-veterans-affairs/health-apis-docker-octopus/developer-utils:latest` Docker image
- Initially, this PR tried to just delete the `Dockerfile.build` file because it was thought that the file wasn't used.  But it turns out that the file is required by the Jenkins build config.  So we fell back to just updating the Docker image that the file points at.

[API-31348] - Remove reference to deprecated Docker image

---

Dockerfile.build

Original Issue :: [API-31348](https://jira.devops.va.gov/browse/API-31348)
- Attempts to fix an SSL cert issue we're seeing when Jenkins goes to build the Master branch.

[API-31348] - Attempt to fix SSL cert issue

---

lib/tasks/lpb.rake

https://jira.devops.va.gov/browse/API-33844
Just adding a wrapper to allow for easier debugging of an error during the first run of the script in qa.

[API-33844] - Add rescue around deeplink error

---

app/models/test_user_email.rb

https://jira.devops.va.gov/browse/API-33844
This will confirm that the Consumer record attached to the User has not been marked as unsubscribed from future emails. While I would typically expect for this to be checked within the task ([potentially here](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/blob/7baa93c41f2b7efc268fce5a6f3af92976c89b2c/lib/tasks/lpb.rake#L569-L577)), given the short timeline and there already being a `begin/rescue` block around this call, we can easily get away with just making the database query more specific as any errors will be caught as a record that we expect should be skipped.

[API-33844] - Confirm unsubscribe is false for export

---

app/views/sandbox_mailer/consumer_sandbox_signup.html.erb

https://jira.devops.va.gov/browse/API-34175
Modifications to the email template failed to properly address CCG signups causing the signups emails from those API types to fail to send while simultaneously still showing the success page on the sandbox signup form. This resolves that bug in the email template.

[API-34175] - Remove dig in favor of direct access to prop

---

app/views/sandbox_mailer/consumer_sandbox_signup.html.erb

Original Issue :: [API-31367](https://jira.devops.va.gov/browse/API-31367)
- Very minor tweaks requested by UX for the Sandbox signup email templates.
**NOTE** :: Once this is deployed to Prod, we'll need to set the `ApiMetadatum.restricted_access_toggle` attribute in LPB to `true` for the following non-CCG/ACG APIs.
- Address Validation
- Appeals Status
- Decision Reviews
- Loan Guaranty

[API-31367] - Minor tweaks to sandbox email templates

---

app/views/sandbox_mailer/consumer_sandbox_signup.html.erb

https://jira.devops.va.gov/browse/API-34321
This updates the sandbox confirmation email to use more supported markup. Mainly the ordered list is changed to a table which simulates an ordered list and also replacing strong tags with b tags because that's more supported for email clients.

[API-34321] - Sandbox confirmation email fixes
