department-of-veterans-affairs/lighthouse-platform-backend

Gemfile
Gemfile.lock
development/kong/deck/seed.yml
docker-compose.yml

Adds a local kong instance to docker-compose.
Updates PUMA for Brakeman.

Add local kong

---

config/application.yml.sample

This PR remove a secret that shouldn't have been committed... The old secret has been deleted

Remove old secret from env samples

---

app/controllers/admin/dashboard_controller.rb
app/views/admin/dashboard/index.html.erb
spec/requests/admin/dashboard_spec.rb

Creates a toggle for Github Auth

Disable GitHub Auth

---

app/views/admin/dashboard/index.html.erb
config/initializers/rails_admin.rb

Opens rails_admin to all - bypass github auth for now

remove checks to open rails_admin in envs

---

app/api/v0/consumers.rb
app/helpers/mailer_helper.rb
app/mailers/sandbox_mailer.rb
app/views/sandbox_mailer/consumer_sandbox_signup.html.erb
app/views/sandbox_mailer/va_profile_sandbox_signup.html.erb
config/application.yml.sample
config/environments/test.rb
spec/api/v0/consumers_spec.rb
spec/factories/api_metadata.rb
spec/factories/internal_sandbox_request.rb
spec/factories/kong_consumer.rb
spec/factories/okta_consumer.rb
spec/factories/sandbox_signup_request.rb
spec/mailers/previews/sandbox_mailer_preview.rb
spec/mailers/sandbox_mailer_spec.rb

Adds the welcome email and va_profile email to sandbox signup.

Api 13797 add emails to sandbox

---

Gemfile.lock

updates puma to pass brakeman.

updates puma

---

README.md

Adds general information about the service
Reference: https://lighthouseva.slack.com/archives/C0190E2PVTQ/p1649701496215789?thread_ts=1649700399.990829&cid=C0190E2PVTQ

Additional README info

---

app/api/v0/consumers.rb

correct env to environment

---

app/api/base.rb

hoping see all cookies rails knows about will help understand what is going on here

more debugging

---

app/api/base.rb
spec/api/v0/consumers_spec.rb

Leaving one line of debugging in place for testing nginx changes to allow cookies going forward.

Revert all but one previous debugging change

---

app/services/kong/base_service.rb

change kong route

---

app/api/v0/consumers.rb
app/api/v0/entities/consumer_entity.rb
spec/api/v0/consumers_spec.rb

add /v0/consumers

---

app/jobs/kong_drift_job.rb
config/initializers/okcomputer.rb

pause prod kong drift logic until a connection to prod kong can be made
also add health checks for prod kong and prod okta

pause prod kong drift logic until connection can be made

---

app/views/production_mailer/support_production_access.html.erb
spec/factories/production_access_request.rb

Corrects nesting error on veteran facing. 
Can preview at `http://localhost:8080/rails/mailers/production_mailer/support_production_access`.

Api 16628 veteran facing

---

config/application.yml.sample
config/environments/test.rb
config/initializers/rails_admin.rb
config/initializers/swagger.rb
config/routes.rb

dvp requires an environment variable be there and the value cant be empty
switching this from a present check to a check for true/false

fix github auth enabled check

---

config/routes.rb

also adds /healthcheck at root (leaves /health_check for system checking during deploy) cause the underscore was bothering me...

makes healthcheck accessible through kong v0 path

---

.rubocop.yml
app/api/utilities.rb
app/jobs/monthly_signups_report_job.rb
app/jobs/weekly_signups_report_job.rb
app/models/event.rb
app/services/slack/report_service.rb
config/initializers/scheduler.rb
spec/api/utilities_spec.rb
spec/jobs/monthly_signups_report_job_spec.rb
spec/jobs/weekly_signups_report_job_spec.rb
spec/services/slack/report_service_spec.rb

Reworks the report service to be able to send weekly and monthly reports.

Api 17027 monthly report

---

app/api/entities/api_environment_entity.rb
spec/api/utilities_spec.rb
spec/factories/apis.rb
spec/factories/events.rb

removes fields that are no longer included within the api_env

remove fields from entity

---

app/api/v0/consumers.rb

removes whitespace from oAuthRedirectURI via `coerce_with`

add strip to oauthredirecturi

---

app/services/slack/report_service.rb
config/environments/production.rb

new event types are causing issues with this query
all sql queries need to filter down to this specific event type

API-17493: Investigate and Fix Slack Sandbox Signup Reporting Issue

---

app/api/v0/providers.rb

content repo change to send base64 encoded content
https://github.com/department-of-veterans-affairs/developer-portal-content/pull/8

allow base64 release notes

---

config/initializers/rails_admin.rb

Based on [this comment](https://github.com/railsadminteam/rails_admin/issues/3025#issuecomment-392513722) seeing if this will fix it.

[API-22785] - List model name as a string

---

app/services/okta/base_service.rb
db/migrate/20230208190820_add_audience_values_v2.rb
db/schema.rb
lib/tasks/aud_values.rake

https://vajira.max.gov/browse/API-21234
Resolve logic error from #241

[API-21234] - Fix auth_server_id method

---

README.md

Updates the `README` file with docs on how the auto-deployment setup functions.

Updates the README with docs about how auto-deployment works

---

.github/workflows/assets/maintenance-request.md

https://vajira.max.gov/browse/API-25262
Related to https://github.com/department-of-veterans-affairs/lighthouse-devops-support/pull/2355
Simple update to MR template. Checkbox remains unchecked as this is just for the very first deploy to an SLA'd environment and not each new release going to an SLA'd environment.

[API-25262] - Update MR template

---

.github/workflows/assets/maintenance-request.md

Teams are unsupported as an assignee of an issue

[API-25262] - MR approvers goes back to a list

---

db/seeds.rb

Original Issue :: [API-23993](https://vajira.max.gov/browse/API-23993)
- Updates the `db/seeds.rb` file to account for the new "Information Architecture" (IA) attributes

[API-23993] - Update seeds file to account for new IA attributes

---

db/migrate/20230701151610_fix_category_url_slug_values.rb
db/schema.rb
db/seeds.rb
lib/tasks/lpb.rake

The logic in the `lpb:seedIAFieldValues` rake task for creating category url_slug values is wrong. This resolves that.

Fix category url_slug fields

---

db/migrate/20230703211827_update_api_descriptions.rb
db/schema.rb
lib/tasks/lpb.rake

[Jira Ticket (API-27816 - Update Explore Page Summaries for 6 APIs)](https://jira.devops.va.gov/browse/API-27816)
This PR updates the descriptions of 6 APIs

Create rake task and migration

---

.gitignore
app/models/test_user_email.rb
app/services/aws_s3_service.rb
db/migrate/20240131034635_test_user_email_export.rb
db/schema.rb
lib/tasks/lpb.rake
spec/factories/test_user_emails.rb
spec/models/test_user_email_spec.rb
spec/services/aws_s3_service_spec.rb
spec/support/vcr_cassettes/aws/s3_put_object.yml

https://jira.devops.va.gov/browse/API-33844
This will scan the events table and output all requests for sandbox access of ACG APIs into a csv with individualized deeplinks for consumers to retrieve the test user data.

[API-33844] - Add rake task for deeplink csv file

---

app/views/sandbox_mailer/consumer_sandbox_signup.html.erb

https://jira.devops.va.gov/browse/API-34321
More overall fixes to the email template including spoofing the ordered list with tables (thanks Outlook) and also removing some spacing. Deduplicated some text in the ACG portion of the template and added the last two lines that related to prod access and contacting support.

[API-34321] - More UX updates to sandbox template

---

app/views/sandbox_mailer/consumer_sandbox_signup.html.erb

https://jira.devops.va.gov/browse/API-34321
Fixing the missing links and got updated UX feedback on spacing and sizing of text.

[API-34321] - Add links and UX updates to sandbox email
